-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hdt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hdt` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hdt` ;

-- -----------------------------------------------------
-- Table `hdt`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hdt`.`person` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `DOB` DATE NULL DEFAULT NULL COMMENT 'Date of birth',
  `BIRTH_CITY` VARCHAR(45) NULL DEFAULT NULL,
  `BIRTH_STATE_CD` VARCHAR(6) NULL DEFAULT NULL,
  `BIRTH_COUNTRY_CD` VARCHAR(6) NULL DEFAULT NULL,
  `HAIR_COLOR_CD` VARCHAR(6) NULL DEFAULT NULL,
  `EYE_COLOR_CD` VARCHAR(6) NULL DEFAULT NULL,
  `ETHNICITY` VARCHAR(45) NULL DEFAULT NULL,
  `FATHER_NAME` VARCHAR(60) NULL DEFAULT NULL,
  `MOTHER_NAME` VARCHAR(60) NULL DEFAULT NULL,
  `STATUS_CD` VARCHAR(6) NULL DEFAULT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(20) NULL DEFAULT NULL,
  `LAST_MODIFIED_DATE` DATETIME NULL DEFAULT NULL,
  `LAST_MODIFIED_BY` VARCHAR(20) NULL DEFAULT NULL,
  `VERSION` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Records in this table represent a person. ';


-- -----------------------------------------------------
-- Table `hdt`.`person_connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hdt`.`person_connection` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CONNECTION_TYPE_CD` VARCHAR(6) NULL DEFAULT NULL,
  `BEGIN_DATE` DATE NULL DEFAULT NULL,
  `END_DATE` DATE NULL DEFAULT NULL,
  `STATUS_CD` VARCHAR(6) NULL DEFAULT NULL,
  `SOURCE_PERSON_ID` BIGINT NULL DEFAULT NULL,
  `RELATED_PERSON_ID` BIGINT NULL DEFAULT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(20) NULL DEFAULT NULL,
  `LAST_MODIFIED_DATE` DATETIME NULL DEFAULT NULL,
  `LAST_MODIFIED_BY` VARCHAR(20) NULL DEFAULT NULL,
  `VERSION` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  INDEX `SOURCE_HUMAN_ID_FK_idx` (`SOURCE_PERSON_ID` ASC) VISIBLE,
  INDEX `RELATED_HUMAN_ID_FK_idx` (`RELATED_PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `RELATED_PERSON_ID_FK`
    FOREIGN KEY (`RELATED_PERSON_ID`)
    REFERENCES `hdt`.`person` (`ID`),
  CONSTRAINT `SOURCE_PERSON_ID_FK`
    FOREIGN KEY (`SOURCE_PERSON_ID`)
    REFERENCES `hdt`.`person` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table connects humans to each other';


-- -----------------------------------------------------
-- Table `hdt`.`person_name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hdt`.`person_name` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `MIDDLE_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `LAST_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `BEGIN_DATE` DATE NULL DEFAULT NULL,
  `END_DATE` DATE NULL DEFAULT NULL,
  `STATUS_CD` VARCHAR(6) NULL DEFAULT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(20) NULL DEFAULT NULL,
  `LAST_MODIFIED_DATE` DATETIME NULL DEFAULT NULL,
  `LAST_MODIFIED_BY` VARCHAR(20) NULL DEFAULT NULL,
  `VERSION` INT NOT NULL DEFAULT '0',
  `PERSON_ID` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `PERSON_ID_FK_idx` (`PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `PERSON_ID_FK`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `hdt`.`person` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 98
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table contains name details for a person';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
